### ISSUE TITLE
Is this supposed to have multiplayer support?

### ISSUE THREAD

**Issue by yasinbread** [R3FR4G/SRB2-Rich-Presence#1]
Whenever I join an online server the RPC game state is just stuck to "Navigating the menus"

**Comment by Refragg** [comment]
Sorry for the late answer, it might be because you're playing with a custom gametype or with mods, this program was designed to work with vanilla stuff mainly

**Comment by yasinbread** [comment]
That doesn't seem to be the case, apparently when joining a vanilla server the RPC doesn't update but hosting one updates it. (Video for reference https://my.namejeff.com/HVr3ibwj.mp4)

**Comment by Refragg** [comment]
Oh alright it makes more sense now, i'll take a look at that

**Comment by Refragg** [comment]
Fixed in the new release, thank you for making me notice
